In [36]:
import numpy as np
A = np.array([[0,0,1,0,0],
              [1,0,1,0,0],
              [0,0,0,0,1],
              [0,1,1,0,0],
              [0,0,0,1,0]])
#A = np.array([[0,0,0,1,1,1],[0,0,0,1,1,0],[0,0,0,0,1,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,1,0,0,0]])
#逆矩陣A.I
#矩陣轉置 A.T
AT = A.T
print("A=",A)
print("AT=",AT)

#A.shape = (5,5)
a0 = ([0.1]) * A.shape[0]
h0 = ([0.1]) * A.shape[0]

# a1 = AT*A*a0
# h1 = A*AT*h0
A1 = np.dot(AT,A)
H1 = np.dot(A,AT)

for i in range(1,21):
    a1 = np.dot(A1,a0)
    a0 = a1
        
    h1 = np.dot(H1,h0)
    h0 = h1
    
    print("第",i,"次的authorities=",a1)
    print("第",i,"次的hubs=       ",h1)


A= [[0 0 1 0 0]
 [1 0 1 0 0]
 [0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 0 1 0]]
AT= [[0 1 0 0 0]
 [0 0 0 1 0]
 [1 1 0 1 0]
 [0 0 0 0 1]
 [0 0 1 0 0]]
第 1 次的authorities= [ 0.2  0.2  0.5  0.1  0.1]
第 1 次的hubs=        [ 0.3  0.4  0.1  0.4  0.1]
第 2 次的authorities= [ 0.7  0.7  1.9  0.1  0.1]
第 2 次的hubs=        [ 1.1  1.5  0.1  1.5  0.1]
第 3 次的authorities= [ 2.6  2.6  7.1  0.1  0.1]
第 3 次的hubs=        [ 4.1  5.6  0.1  5.6  0.1]
第 4 次的authorities= [  9.7   9.7  26.5   0.1   0.1]
第 4 次的hubs=        [ 15.3  20.9   0.1  20.9   0.1]
第 5 次的authorities= [ 36.2  36.2  98.9   0.1   0.1]
第 5 次的hubs=        [ 57.1  78.    0.1  78.    0.1]
第 6 次的authorities= [  1.35100000e+02   1.35100000e+02   3.69100000e+02   1.00000000e-01
   1.00000000e-01]
第 6 次的hubs=        [  2.13100000e+02   2.91100000e+02   1.00000000e-01   2.91100000e+02
   1.00000000e-01]
第 7 次的authorities= [  5.04200000e+02   5.04200000e+02   1.37750000e+03   1.00000000e-01
   1.00000000e-01]
第 7 次的hubs=        [  7.95300000e+02   1.08640000e+03   1.00

In [31]:
A = np.array([[0,0,1,0,0],[1,0,1,0,0],[0,0,0,0,1],[0,1,1,0,0],[0,0,0,1,0]])
a0 = ([0.1])*5
print(a0)
print(A.shape[0])

[0.1, 0.1, 0.1, 0.1, 0.1]
5
